api: true

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic_conf.yml
    watch: true

log:
  level: INFO

entryPoints:
  insecureweb:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: secureweb
          scheme: https
  secureweb:
    address: ":443"
    http:
      tls: true